apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      environment: development
      version: latest