apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-staging

resources:
- ../../base

namePrefix: staging-

labels:
- includeSelectors: true
  pairs:
    environment: staging
    version: v0.9.0

configMapGenerator:
- name: webapp-config
  behavior: replace
  literals:
  - database_url=postgres://staging-db:5432/webapp_staging
  - log_level=WARN
  - cache_ttl=600