apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-prod

resources:
- ../../base

namePrefix: prod-
nameSuffix: -stable

labels:
- includeSelectors: true
  pairs:
    environment: production
    version: v1.0.0
    tier: frontend

patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    name: webapp